### ISSUE TITLE
The value passed in ng-if directive should be swapped

### ISSUE THREAD

**Issue by ibrahimuta** [saadather/WirlZy#9]
@zamamohammed  : c51fa054859a0e5d2c35ed92e1c6a2cb44f36cae : In Navbar.html line 21 & 22
     ng-if="locale === 'en-US'" ng-click="setLocale('ar-SA')
     ng-if="locale === 'ar-SA'" ng-click="setLocale('en-US')

In the above code en-US should be swapped with ar-SA. Let me know if this need to be corrected.

**Comment by mohammedzamakhan** [comment]
No its correct, the the locale is US, then on the button click we change the language to ar-SA.

**Comment by ibrahimuta** [comment]
ok, I was confused. Thanks for clarification.

On Wed, Sep 2, 2015 at 7:56 PM, Zama Khan Mohammed <notifications@github.com

> wrote:
> 
> No its correct, the the locale is US, then on the button click we change
> the language to ar-SA.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saadather/WirlZy/issues/9#issuecomment-137287071.

## 

Thanks,

Ibrahim Khaleelullah
